version: '3.8'

services:
  backend:
    image: rehasliamsi/weatherfetcher-backend:latest
    ports:
      - "8080:8080"
    networks:
      - weather-net
    environment:
      - openweathermap.api.key=${OPENWEATHERMAP_API_KEY}

  frontend:
    image: rehasliamsi/weatherfetcher-frontend:latest
    ports:
      - "3000:80"
    networks:
      - weather-net
    depends_on:
      - backend

networks:
  weather-net:
