version: '3.8'

services:
  backend:
    build:
      context: ./weather-backend
    ports:
      - "8080:8080"
    networks:
      - weather-net

  frontend:
    build:
      context: ./weather-frontend
    ports:
      - "3000:80"
    networks:
      - weather-net
    depends_on:
      - backend

networks:
  weather-net:
